steps:
  - group: ":card_index_dividers: Diffusion X2V Model Test"
    key: nightly-diffusion-x2v-group
    depends_on: upload-nightly-pipeline
    if: >-
      build.env("NIGHTLY") == "1" ||
      build.pull_request.labels includes "nightly-test" ||
      build.pull_request.labels includes "diffusion-x2v-test"
    steps:
      - label: ":full_moon: Diffusion X2V · Function Test"
        agents:
          queue: "ascend-a2b3"
          resource_class: "npu-4"
        image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
        plugins:
          - kubernetes:
              podSpecPatch:
                imagePullSecrets:
                  - name: swr-secret
        env:
          VLLM_WORKER_MULTIPROC_METHOD: spawn
          HF_TOKEN: "${HF_TOKEN}"
        commands:
          - pytest -s -v tests/e2e/online_serving/test_wan22_expansion.py -k npu_i2v --run-level "full_model"
