ARG VLLM_BASE_IMAGE=vllm/vllm-openai
ARG VLLM_BASE_TAG=v0.19.0
FROM ${VLLM_BASE_IMAGE}:${VLLM_BASE_TAG}
ARG APP_DIR=/workspace/vllm-omni
WORKDIR ${APP_DIR}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y espeak-ng git sox libsox-fmt-all jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN uv pip install --system ".[dev]"

RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
