model_type: qwen3_tts
async_chunk: true

stages:
  - stage_id: 0
    model_stage: qwen3_tts
    stage_type: llm
    is_comprehension: true
    input_sources: []
    worker_type: ar
    scheduler_cls: vllm_omni.core.sched.omni_ar_scheduler.OmniARScheduler
    runtime:
      devices: "0"
    engine_args:
      max_num_seqs: 10
      model_arch: Qwen3TTSTalkerForConditionalGeneration
      hf_overrides:
        architectures: [Qwen3TTSTalkerForConditionalGeneration]
      enforce_eager: false
      trust_remote_code: true
      async_scheduling: true
      enable_prefix_caching: false
      engine_output_type: latent
      gpu_memory_utilization: 0.08
      distributed_executor_backend: "mp"
      max_num_batched_tokens: 512
      max_model_len: 4096
      custom_process_next_stage_input_func: vllm_omni.model_executor.stage_input_processors.qwen3_tts.talker2code2wav_async_chunk
    output_connectors:
      to_stage_1: connector_of_shared_memory
    default_sampling_params:
      temperature: 0.9
      top_k: 50
      max_tokens: 4096
      seed: 42
      detokenize: false
      repetition_penalty: 1.05
      stop_token_ids: [2150]

  - stage_id: 1
    model_stage: code2wav
    stage_type: llm
    input_sources: [0]
    worker_type: generation
    scheduler_cls: vllm_omni.core.sched.omni_generation_scheduler.OmniGenerationScheduler
    final_output: true
    final_output_type: audio
    runtime:
      devices: "0"
    engine_args:
      max_num_seqs: 1
      model_arch: Qwen3TTSCode2Wav
      hf_overrides:
        architectures: [Qwen3TTSCode2Wav]
      enforce_eager: true
      trust_remote_code: true
      async_scheduling: true
      enable_prefix_caching: false
      engine_output_type: audio
      gpu_memory_utilization: 0.08
      distributed_executor_backend: "mp"
      max_num_batched_tokens: 65536
      max_model_len: 65536
    input_connectors:
      from_stage_0: connector_of_shared_memory
    tts_args:
      max_instructions_length: 500
    default_sampling_params:
      temperature: 0.0
      top_p: 1.0
      top_k: -1
      max_tokens: 65536
      seed: 42
      detokenize: true
      repetition_penalty: 1.0

connectors:
  connector_of_shared_memory:
    name: SharedMemoryConnector
    extra:
      shm_threshold_bytes: 65536
      codec_streaming: true
      connector_get_sleep_s: 0.01
      connector_get_max_wait_first_chunk: 3000
      connector_get_max_wait: 300
      codec_chunk_frames: 25
      # Match the decoder sliding attention window to avoid chunk-boundary noise.
      codec_left_context_frames: 72

edges:
  - from: 0
    to: 1
    window_size: -1
